Refactor Telegram upload script in workflow

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -129,24 +129,25 @@ jobs:
         sha256sum Kernel-KSU-SUSFS.zip > checksum.txt
 
     - name: 📤 Upload to Telegram
-      run: |
+    run: |
        cd ak3
-       
-          if [ ! -f "Kernel-KSU-SUSFS.zip" ]; then
-          echo "Error: Kernel-KSU-SUSFS.zip tidak ditemukan!"
-          exit 1
-         fi
-         
-         if [ ! -f "checksum.txt" ]; then
-         echo "Error: checksum.txt tidak ditemukan!"
-         exit 1
-         fi 
-         
-         if [ -z "${{ secrets.BOT_TOKEN }}" ] || [ -z "${{ secrets.CHAT_ID }}" ]; then
-         echo "Error: BOT_TOKEN atau CHAT_ID belum diset di repository secrets!"
-         exit 1
-         fi
-         
-         curl --fail -F document=@Kernel-KSU-SUSFS.zip \
-         -F caption="Build Success GKI 5.10 KSU Next + SUSFS ThinLTO\n\n$(cat checksum.txt)" \
-         "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}"
+
+       if [ ! -f "Kernel-KSU-SUSFS.zip" ]; then
+       echo "Error: Kernel-KSU-SUSFS.zip tidak ditemukan!"
+       exit 1
+       fi
+
+       if [ ! -f "checksum.txt" ]; then
+       echo "Error: checksum.txt tidak ditemukan!"
+       exit 1
+       fi
+
+       if [ -z "${{ secrets.BOT_TOKEN }}" ] || [ -z "${{ secrets.CHAT_ID }}" ]; then
+       echo "Error: BOT_TOKEN atau CHAT_ID belum diset di repository secrets!"
+       exit 1
+       fi
+
+       curl --fail -F document=@Kernel-KSU-SUSFS.zip \
+       -F caption="Build Success GKI 5.10 KSU Next + SUSFS ThinLTO\n\n$(cat checksum.txt)" \
+       "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}"
+      
